#!/bin/sh
#
# chkconfig: - 91 35
# description: Starts and stops the abaqus documentation daemon
# processname: monitor.x
#

BASEDIR=/opt/CAE
KIND="Abaqus doc"

# Source function library.
if [ -f /etc/init.d/functions ] ; then
  . /etc/init.d/functions
elif [ -f /etc/rc.d/init.d/functions ] ; then
  . /etc/rc.d/init.d/functions
else
  exit 1
fi

# Avoid using root's TMPDIR
unset TMPDIR

RETVAL=0

start() {
	echo -n $"Starting $KIND services: "
	daemon $BASEDIR/Documentation/bin/monitor
	RETVAL=$?
	echo
	return $RETVAL
}	

stop() {
	echo -n $"Shutting down $KIND services: "
	killproc monitor.x
	RETVAL=$?
	echo
	return $RETVAL
}	

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  status)
  	status monitor.x
	;;
  restart)
  	stop
	start
	;;
  *)
	echo $"Usage: $0 {start|stop|restart|status}"
	exit 2
esac

exit $?
